# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 765)
        MainWindow.setStyleSheet("background-color: rgb(255, 67, 67);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.aposta = QtWidgets.QLineEdit(self.centralwidget)
        self.aposta.setGeometry(QtCore.QRect(450, 390, 171, 41))
        self.aposta.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.aposta.setObjectName("aposta")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(280, 510, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.result.setFont(font)
        self.result.setStyleSheet("color: rgb(255, 255, 30);")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(470, 450, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn.setFont(font)
        self.btn.setStyleSheet("color: rgb(252, 255, 43);")
        self.btn.setObjectName("btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 0, 500, 358))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("triguin.png"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result.setText(_translate("MainWindow", "முட்டாள் :), முட்டாள்தனமான பந்தயம்"))
        self.btn.setText(_translate("MainWindow", "பந்தயம்"))
